version: '3.1'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: transparency

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080